{% set name = "transformers" %}

package:
  name: "{{ name|lower }}"
  version: "conda"

source:
  path: ../../

requirements:
  host:
    - python x.x
    - pip
    - numpy
    - dataclasses
    - packaging
    - filelock
    - requests
    - tqdm >=4.27
    - sacremoses
    - regex !=2019.12.17
    - protobuf
  run:
    - python x.x
    - numpy
    - dataclasses
    - packaging
    - filelock
    - requests
    - tqdm >=4.27
    - sacremoses
    - regex !=2019.12.17
    - protobuf

test:
  imports:
    - transformers

about:
  home: https://huggingface.co
  license: Apache License 2.0
  license_file: LICENSE
  summary: "🤗Transformers: State-of-the-art Natural Language Processing for Pytorch and TensorFlow 2.0."
